SELECT NOMEPESSOA, SOBRENOME, IDADE, FK_GRUPO_IDGRUPO, IDGRUPO, NOMEGRUPO
FROM PESSOA, GRUPO
WHERE FK_GRUPO_IDGRUPO = IDGRUPO;
-- ******************************************************************
SELECT NOMEPESSSOA,SOBRENOME,IDADE, FK_GRUPO_IDGRUPO, IDGRUPO, NOMEGRUPO
FROM GRUPO
INNER LEFT JOIN GRUPO ON FK_GRUPO_IDGRUPO = IDGRUPO